name: upscayl
base: core22
version: 2.9.4
summary: Free and Open Source AI Image Upscaler
description: |
    A Free and Open Source AI Image Upscaler
    Upscayl is a cross-platform application built with the Linux-first philosophy.
    This is not an official build.

    Source: https://github.com/upscayl/upscayl
    Snap-Source: https://github.com/upscayl/snap

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    build-for: amd64

apps:
  upscayl:
    command: opt/Upscayl/upscayl --no-sandbox
    plugs: [home, x11, desktop, removable-media, shared-memory, opengl, network ]
    extensions: [ gnome ]
    environment:
       VK_ICD_FILENAMES: "/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon.x86_64.json:$SNAP/usr/share/vulkan/icd.d/intel_icd.x86_64.json"

plugs:
  shared-memory:
    private: true

parts:
  main:
    source: https://github.com/upscayl/upscayl/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/upscayl-$SNAPCRAFT_PROJECT_VERSION-linux.deb
    plugin: dump
    source-type: deb
    override-build: |
      craftctl default
    stage-packages:
       - libgbm1
       - libgtk-3-0
       - libxrandr2
       - libnss3
       - libnotify4
       - libxss1
       - libxtst6
       - xdg-utils
       - libatspi2.0-0
       - libuuid1
       - libsecret-1-0
       - libappindicator3-1
       - desktop-file-utils
       - libvulkan1
       - mesa-vulkan-drivers
lint:
  ignore:
    - library

layout:
  /usr/share/vulkan:
    symlink: $SNAP/usr/share/vulkan
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_intel.so:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_intel.so
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_radeon.so:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_lvp.so
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_lvp.so:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_lvp.so
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libGLX_nvidia.so.0:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libGLX_nvidia.so.0
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
